### ISSUE TITLE
internal error 2

### ISSUE THREAD

**Issue by secretmango** [ooflet/Mi-Create#28]
```
Internal error! Please report as a bug.

Traceback (most recent call last):
  File "/var/home/user/Git/Mi-Create/src/./main.py", line 1173, in <lambda>
    canvas.scene().selectionChanged.connect(lambda: self.updateProjectSelections("canvas"))
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/user/Git/Mi-Create/src/./main.py", line 1065, in updateProjectSelections
    self.updateProperties(currentCanvasSelected[0],
  File "/var/home/user/Git/Mi-Create/src/./main.py", line 780, in updateProperties
    self.propertiesWidget.loadProperties(self.propertyJson[itemType], currentProject["project"], item,
  File "/var/home/user/Git/Mi-Create/src/widgets/properties.py", line 540, in loadProperties
    self.addProperties(properties["properties"], project, widgetName, resourceList, None, device)
  File "/var/home/user/Git/Mi-Create/src/widgets/properties.py", line 333, in addProperties
    self.addProperties(property, project, widgetName, resourceList, categoryItem, device)  # Recursively add sub-categories
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/user/Git/Mi-Create/src/widgets/properties.py", line 461, in addProperties
    createInput(index)
  File "/var/home/user/Git/Mi-Create/src/widgets/properties.py", line 442, in createInput
    imageInput = self.createResourceEdit(text, False, resourceList, True)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/user/Git/Mi-Create/src/widgets/properties.py", line 195, in createResourceEdit
    resourceEdit.setCurrentText(text)
TypeError: setCurrentText(self, text: Optional[str]): argument 1 has unexpected type 'list'
```

again changing some data type stuff

**Comment by ooflet** [comment]
Could you send your .fprj file?

**Comment by secretmango** [comment]
yeah no problem.

[minimal-1.fprj.zip](https://github.com/user-attachments/files/17007431/minimal-1.fprj.zip)

**Comment by ooflet** [comment]
Fixed, may I ask what you did to get the error? It doesn't seems to be an error that could spontaneously happen by the program 😅
